on:
  push:
    branches:[main]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@5

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          
      - name: Install dependecies
        run: npm install

      - name: Run tests
        run: npm test
